// Real estate glossary — original definitions in plain language. Hawaii-specific
// terms flagged. Useful for cold review before exam.

export interface GlossaryEntry {
  term: string;
  definition: string;
  category: 'national' | 'hawaii' | 'math' | 'finance' | 'agency' | 'contracts' | 'title';
  hawaiiNote?: string;
}

export const GLOSSARY: GlossaryEntry[] = [
  // ─── National foundational ───
  { term: 'Acceleration clause', definition: 'Mortgage provision allowing lender to demand full balance on default.', category: 'finance' },
  { term: 'Accretion', definition: 'Gradual addition of soil to land by natural causes; the new soil belongs to the owner.', category: 'national' },
  { term: 'Acknowledgment', definition: 'Notarized statement that signature was made voluntarily. Required for recording.', category: 'title' },
  { term: 'Acre', definition: '43,560 square feet.', category: 'math' },
  { term: 'Adjustable Rate Mortgage (ARM)', definition: 'Loan with rate that adjusts on a schedule based on an index plus margin.', category: 'finance' },
  { term: 'Ad valorem tax', definition: 'Tax based on assessed value (e.g., property tax).', category: 'national' },
  { term: 'Adverse possession', definition: 'Acquiring title by open, notorious, hostile, continuous occupation for the statutory period.', category: 'title' },
  { term: 'Agency', definition: 'Legal relationship where one person acts on behalf of another.', category: 'agency' },
  { term: 'Agreement of Sale (AOS)', definition: 'Hawaii installment land contract; buyer occupies, seller holds title until paid.', category: 'hawaii', hawaiiNote: 'Common alternative to bank financing.' },
  { term: 'Alienation clause', definition: 'Loan provision triggering due-on-sale on transfer.', category: 'finance' },
  { term: 'Amortization', definition: 'Gradual loan repayment via periodic principal-and-interest payments.', category: 'finance' },
  { term: 'AOAO', definition: 'Association of Apartment Owners — Hawaii term for condo HOA.', category: 'hawaii' },
  { term: 'APR', definition: 'Annual Percentage Rate. Loan cost including interest + points + fees.', category: 'finance' },
  { term: 'Appraisal', definition: 'Licensed appraiser\'s opinion of value. Required for federally related transactions.', category: 'national' },
  { term: 'Appurtenant', definition: 'Attached to or running with the land (e.g., easement appurtenant).', category: 'national' },
  { term: 'Assessed value', definition: 'Tax value placed on property by county assessor. Often less than market value.', category: 'national' },
  { term: 'Assignment', definition: 'Transfer of contract rights to another party.', category: 'contracts' },
  { term: 'Attornment', definition: 'Tenant\'s acknowledgment of new owner as landlord.', category: 'national' },
  { term: 'Bilateral contract', definition: 'Both parties make promises to each other.', category: 'contracts' },
  { term: 'Blanket mortgage', definition: 'One mortgage covering multiple parcels with partial release clause.', category: 'finance' },
  { term: 'Blockbusting', definition: 'Inducing sales by representing protected-class entry. Fair housing violation.', category: 'national' },
  { term: 'BOC', definition: 'Bureau of Conveyances — Hawaii\'s Regular System title office.', category: 'hawaii' },
  { term: 'Bundle of rights', definition: 'Set of legal rights of ownership: possess, use, enjoy, exclude, dispose.', category: 'national' },
  { term: 'Capacity', definition: 'Legal ability to contract.', category: 'contracts' },
  { term: 'Capitalization rate', definition: 'NOI ÷ Value. Higher rate = higher risk or lower price.', category: 'math' },
  { term: 'Caveat emptor', definition: '"Let the buyer beware" — largely supplanted by mandatory disclosure laws.', category: 'national' },
  { term: 'CC&Rs', definition: 'Covenants, Conditions, and Restrictions. Private deed-based rules running with land.', category: 'national' },
  { term: 'CERCLA', definition: 'Superfund. Federal hazardous-waste cleanup law with strict liability.', category: 'national' },
  { term: 'Chain of title', definition: 'Recorded history of ownership. Gaps = clouds.', category: 'title' },
  { term: 'Closing Disclosure', definition: 'Federal form summarizing loan terms + closing costs. Delivered 3 days before closing.', category: 'finance' },
  { term: 'Cloud on title', definition: 'Defect or unresolved claim affecting marketability.', category: 'title' },
  { term: 'CMA', definition: 'Comparative Market Analysis. Agent-prepared pricing recommendation.', category: 'national' },
  { term: 'COALD', definition: 'Care, Obedience, Accounting, Loyalty, Disclosure. Five fiduciary duties.', category: 'agency' },
  { term: 'Commingling', definition: 'Mixing trust funds with personal funds. License-law violation.', category: 'agency' },
  { term: 'Common elements', definition: 'Condo property shared by all unit owners (lobby, pool, roof).', category: 'hawaii' },
  { term: 'Comparables (comps)', definition: 'Recent sales used to estimate subject\'s value.', category: 'national' },
  { term: 'Condemnation', definition: 'Government\'s exercise of eminent domain.', category: 'national' },
  { term: 'Conditional use', definition: 'Use allowed in zone subject to specific conditions/permit.', category: 'national' },
  { term: 'Condominium', definition: 'Fee ownership of unit + undivided interest in common elements.', category: 'national' },
  { term: 'Consideration', definition: 'Something of value exchanged in a contract.', category: 'contracts' },
  { term: 'Contingency', definition: 'Condition that must be met for contract to proceed.', category: 'contracts' },
  { term: 'Conversion', definition: 'Using trust funds for own benefit. Felony in most states.', category: 'agency' },
  { term: 'Conveyance', definition: 'Transfer of real property interest.', category: 'title' },
  { term: 'Conveyance tax', definition: 'Hawaii state tax on real property transfers. Tiered rate.', category: 'hawaii' },
  { term: 'Cooperative', definition: 'Own shares in corporation that owns building + proprietary lease.', category: 'national' },
  { term: 'Counteroffer', definition: 'Rejection + new offer. Cancels original.', category: 'contracts' },
  { term: 'Covenant', definition: 'Promise running with land. Binds future owners.', category: 'national' },
  { term: 'CPR', definition: 'Condominium Property Regime. Multiple units on one lot, each with TMK. Hawaii-specific.', category: 'hawaii' },
  { term: 'Curtesy', definition: 'Common-law husband\'s interest in deceased wife\'s real property. Largely abolished.', category: 'national' },
  { term: 'Datum', definition: 'Reference point for elevation measurements.', category: 'national' },
  { term: 'DCCA', definition: 'Hawaii Department of Commerce and Consumer Affairs. Oversees REC.', category: 'hawaii' },
  { term: 'Dedication', definition: 'Voluntary transfer of private land to public use.', category: 'national' },
  { term: 'Deed', definition: 'Document transferring title from grantor to grantee.', category: 'title' },
  { term: 'Deed restriction', definition: 'Private use restriction in deed. Runs with land.', category: 'title' },
  { term: 'Default', definition: 'Failure to perform contract obligation.', category: 'contracts' },
  { term: 'Delivery', definition: 'Transfer of deed with intent to convey. Required for valid transfer.', category: 'title' },
  { term: 'Depreciation (appraisal)', definition: 'Loss in value from physical, functional, or external causes.', category: 'national' },
  { term: 'Discount points', definition: 'Prepaid interest. 1 point = 1% of loan. Lowers rate.', category: 'finance' },
  { term: 'DROA', definition: 'Deposit Receipt Offer and Acceptance — Hawaii standard residential purchase form.', category: 'hawaii' },
  { term: 'Dual agency', definition: 'One agent represents both buyer and seller. Requires written informed consent.', category: 'agency' },
  { term: 'DUST', definition: 'Demand, Utility, Scarcity, Transferability. Four characteristics required for value.', category: 'national' },
  { term: 'Earnest money', definition: 'Buyer\'s good-faith deposit, typically held by escrow.', category: 'contracts' },
  { term: 'Easement', definition: 'Right to use another\'s land. Appurtenant runs with land; in gross is personal.', category: 'national' },
  { term: 'ECOA', definition: 'Equal Credit Opportunity Act. Bans lending discrimination.', category: 'finance' },
  { term: 'Emblements', definition: 'Tenant\'s annual crops; treated as personal property.', category: 'national' },
  { term: 'Eminent domain', definition: 'Government power to take private property for public use with just compensation.', category: 'national' },
  { term: 'Encroachment', definition: 'Unauthorized physical intrusion onto another\'s property.', category: 'national' },
  { term: 'Encumbrance', definition: 'Non-possessory claim affecting property (lien, easement, restriction).', category: 'national' },
  { term: 'Equity', definition: 'Property value minus liens.', category: 'finance' },
  { term: 'Escheat', definition: 'Property reverts to state when owner dies intestate with no heirs.', category: 'national' },
  { term: 'Escrow', definition: 'Neutral third party holding funds + documents until conditions met.', category: 'national' },
  { term: 'Estate', definition: 'Interest in land. Includes fee simple, life estate, leasehold.', category: 'national' },
  { term: 'Estoppel', definition: 'Bar against asserting a position contrary to one\'s prior conduct.', category: 'contracts' },
  { term: 'Exclusive Agency Listing', definition: 'Broker earns commission unless seller produces buyer.', category: 'agency' },
  { term: 'Exclusive Right to Sell', definition: 'Broker earns regardless of who finds buyer.', category: 'agency' },
  { term: 'Fair Housing Act', definition: 'Federal law banning housing discrimination on 7 protected classes.', category: 'national' },
  { term: 'Fee simple absolute', definition: 'Greatest possible ownership interest. Perpetual, inheritable, unconditional.', category: 'national' },
  { term: 'FHA', definition: 'Federal Housing Administration. Insures low-down-payment loans.', category: 'finance' },
  { term: 'Fiduciary', definition: 'Person owing duties of trust (care, loyalty, etc.).', category: 'agency' },
  { term: 'FIRPTA', definition: 'Federal Foreign Investment in Real Property Tax Act. 15% withholding on foreign sellers.', category: 'finance' },
  { term: 'Fixture', definition: 'Item that has become real property by attachment, adaptation, or intent.', category: 'national' },
  { term: 'Foreclosure', definition: 'Lender\'s remedy on default. Judicial or non-judicial.', category: 'finance' },
  { term: 'Fraud', definition: 'Intentional misrepresentation of material fact causing harm.', category: 'contracts' },
  { term: 'Freehold estate', definition: 'Indeterminate-duration estate (fee, life estate). Contrast leasehold.', category: 'national' },
  { term: 'GET', definition: 'Hawaii General Excise Tax. Applies to real estate commissions and rents.', category: 'hawaii' },
  { term: 'GIM', definition: 'Gross Income Multiplier. Sale Price ÷ Annual Gross Income.', category: 'math' },
  { term: 'Grantor / Grantee', definition: 'Grantor = transferor. Grantee = recipient.', category: 'title' },
  { term: 'GRM', definition: 'Gross Rent Multiplier. Sale Price ÷ Monthly Gross Rent.', category: 'math' },
  { term: 'HARPTA', definition: 'Hawaii Real Property Tax Act. 7.25% withholding on non-resident seller.', category: 'hawaii' },
  { term: 'Highest and best use', definition: 'Legally permissible, physically possible, financially feasible, maximally productive use.', category: 'national' },
  { term: 'HOA', definition: 'Homeowners Association. Manages common-interest community.', category: 'national' },
  { term: 'HRS 467', definition: 'Hawaii Real Estate Brokers and Salespersons statute.', category: 'hawaii' },
  { term: 'HRS 514B', definition: 'Hawaii modern Condominium Property Act.', category: 'hawaii' },
  { term: 'HRS 521', definition: 'Hawaii Residential Landlord-Tenant Code.', category: 'hawaii' },
  { term: 'HRS 508D', definition: 'Hawaii Mandatory Seller Disclosures statute.', category: 'hawaii' },
  { term: 'HRS 515', definition: 'Hawaii state fair housing statute. Adds classes beyond federal.', category: 'hawaii' },
  { term: 'Hui', definition: 'Traditional Hawaiian co-ownership of land, often family-held.', category: 'hawaii' },
  { term: 'Hypothecation', definition: 'Pledging property as security without giving up possession.', category: 'finance' },
  { term: 'Implied agency', definition: 'Agency created by parties\' conduct without express agreement.', category: 'agency' },
  { term: 'In-gross easement', definition: 'Easement held by a person, not attached to a specific parcel.', category: 'national' },
  { term: 'Joint tenancy', definition: 'Co-ownership with right of survivorship. Requires four unities.', category: 'national' },
  { term: 'Land Court', definition: 'Hawaii\'s Torrens-style registered title system. TCT is conclusive.', category: 'hawaii' },
  { term: 'Latent defect', definition: 'Hidden defect not discoverable on reasonable inspection.', category: 'national' },
  { term: 'Lease', definition: 'Contract transferring possession + use for term in exchange for rent.', category: 'contracts' },
  { term: 'Leasehold estate', definition: 'Tenant\'s right to possess and use property for term.', category: 'national' },
  { term: 'Lessor / Lessee', definition: 'Landlord / Tenant.', category: 'national' },
  { term: 'Lien', definition: 'Monetary encumbrance attaching to property as security for debt.', category: 'national' },
  { term: 'Life estate', definition: 'Ownership for duration of measuring life. Reverts to remainderman.', category: 'national' },
  { term: 'Liquidated damages', definition: 'Pre-agreed damages amount. Often the earnest money in real estate.', category: 'contracts' },
  { term: 'Listing agreement', definition: 'Contract creating broker-seller relationship.', category: 'agency' },
  { term: 'LTV', definition: 'Loan-to-Value. Loan ÷ Value. PMI required above 80% conventional.', category: 'finance' },
  { term: 'Marketable title', definition: 'Title free of significant clouds, acceptable to a reasonable buyer.', category: 'title' },
  { term: 'Material fact', definition: 'Fact a reasonable buyer/seller would consider important.', category: 'national' },
  { term: 'Mechanic\'s lien', definition: 'Contractor/supplier lien for unpaid work or materials. HRS 507 in Hawaii.', category: 'hawaii' },
  { term: 'Megan\'s Law', definition: 'Sex offender registration disclosure. State-specific agent duty rules.', category: 'national' },
  { term: 'Mill rate', definition: 'Property tax rate. Tax = Assessed Value × (mills ÷ 1,000).', category: 'math' },
  { term: 'Misrepresentation', definition: 'False statement of material fact. Innocent, negligent, or fraudulent.', category: 'agency' },
  { term: 'Mortgage', definition: 'Security instrument creating lender\'s lien on property.', category: 'finance' },
  { term: 'Net listing', definition: 'Broker keeps amount above seller\'s minimum. Disfavored or banned.', category: 'agency' },
  { term: 'NOI', definition: 'Net Operating Income. Gross Income − Vacancy − Operating Expenses.', category: 'math' },
  { term: 'Novation', definition: 'Substitution of new party or new contract by mutual agreement.', category: 'contracts' },
  { term: 'Offer', definition: 'Definite proposal communicated with intent to be bound on acceptance.', category: 'contracts' },
  { term: 'Option contract', definition: 'Right (not obligation) to buy at stated price within stated time.', category: 'contracts' },
  { term: 'Patent defect', definition: 'Obvious defect visible on reasonable inspection.', category: 'national' },
  { term: 'Periodic tenancy', definition: 'Lease that renews automatically (month-to-month).', category: 'national' },
  { term: 'PITI', definition: 'Principal, Interest, Taxes, Insurance. Total monthly housing payment.', category: 'finance' },
  { term: 'PMI', definition: 'Private Mortgage Insurance. Required above 80% LTV conventional.', category: 'finance' },
  { term: 'PMM', definition: 'Purchase Money Mortgage. Seller-financed mortgage at sale.', category: 'finance' },
  { term: 'Police power', definition: 'Government authority to regulate for health, safety, welfare. Source of zoning.', category: 'national' },
  { term: 'Power of attorney', definition: 'Written authority for another to act for you.', category: 'agency' },
  { term: 'Prepayment penalty', definition: 'Fee for paying off loan early. Restricted on most owner-occupied mortgages.', category: 'finance' },
  { term: 'Principal', definition: '(1) Loan amount. (2) Person agent represents.', category: 'finance' },
  { term: 'Probate', definition: 'Court process administering deceased\'s estate.', category: 'title' },
  { term: 'Procuring cause', definition: 'Origin of unbroken chain producing sale. Determines commission entitlement.', category: 'agency' },
  { term: 'Property management', definition: 'General agency: collect rents, maintain property, handle tenants.', category: 'agency' },
  { term: 'Proration', definition: 'Splitting shared expenses at closing.', category: 'math' },
  { term: 'PUD', definition: 'Planned Unit Development. Own lot + share in common areas.', category: 'national' },
  { term: 'Puffing', definition: 'Subjective sales talk. Not actionable as misrepresentation.', category: 'agency' },
  { term: 'Quitclaim deed', definition: 'Conveys whatever interest grantor has. No warranties.', category: 'title' },
  { term: 'Real Estate Commission (REC)', definition: 'Hawaii regulator. Sets rules, investigates, disciplines licensees.', category: 'hawaii' },
  { term: 'Real property', definition: 'Land + permanent attachments + ownership rights.', category: 'national' },
  { term: 'Recording', definition: 'Filing document with county recorder. Provides constructive notice.', category: 'title' },
  { term: 'Redlining', definition: 'Refusing to lend/insure in protected-class areas. Illegal.', category: 'national' },
  { term: 'Rescission', definition: 'Termination of contract returning parties to pre-contract position.', category: 'contracts' },
  { term: 'RESPA', definition: 'Real Estate Settlement Procedures Act. Loan Estimate + Closing Disclosure rules.', category: 'finance' },
  { term: 'Reverse mortgage', definition: 'Loan against home equity for seniors. Repaid when borrower dies/moves/sells.', category: 'finance' },
  { term: 'Riparian rights', definition: 'Rights of owner of land bordering a watercourse.', category: 'national' },
  { term: 'Salesperson license', definition: 'Hawaii entry-level license. 18+, 60-hr course, PSI exam, sponsoring broker.', category: 'hawaii' },
  { term: 'Sellers market', definition: 'Demand exceeds supply; prices rise.', category: 'national' },
  { term: 'Setback', definition: 'Required distance between structure and property line.', category: 'national' },
  { term: 'Severalty', definition: 'Sole ownership by one person or entity.', category: 'national' },
  { term: 'SMA', definition: 'Special Management Area. Hawaii coastal-zone regulation.', category: 'hawaii' },
  { term: 'Specific performance', definition: 'Court orders actual conveyance. Buyer\'s remedy for seller breach.', category: 'contracts' },
  { term: 'Spot zoning', definition: 'Singling out one parcel for different treatment. Generally unconstitutional.', category: 'national' },
  { term: 'Statute of Frauds', definition: 'Real estate contracts must be in writing.', category: 'contracts' },
  { term: 'Steering', definition: 'Channeling buyers based on protected class. Fair housing violation.', category: 'national' },
  { term: 'Stigmatized property', definition: 'Property with non-physical issue (death, crime). Disclosure rules vary by state.', category: 'national' },
  { term: 'Subagency', definition: 'Agent\'s authority delegated to another agent.', category: 'agency' },
  { term: 'Subdivision', definition: 'Division of land into lots for sale or development.', category: 'national' },
  { term: 'Subordination', definition: 'Voluntarily lowering lien priority to allow new senior lien.', category: 'finance' },
  { term: 'Survey', definition: 'Professional measurement and mapping of parcel boundaries.', category: 'national' },
  { term: 'TCT', definition: 'Transfer Certificate of Title. Hawaii Land Court conclusive title document.', category: 'hawaii' },
  { term: 'Tenancy at will', definition: 'Lease terminable by either party at any time.', category: 'national' },
  { term: 'Tenancy by the entirety', definition: 'Spousal co-ownership with survivorship + creditor protection.', category: 'national' },
  { term: 'Tenancy in common', definition: 'Co-ownership with separate inheritable shares. No survivorship.', category: 'national' },
  { term: 'Time is of the essence', definition: 'Deadlines strictly enforced. Late performance = breach.', category: 'contracts' },
  { term: 'Time share', definition: 'Right to occupy unit for set period each year.', category: 'national', hawaiiNote: 'HRS 514E governs disclosures and 7-day rescission.' },
  { term: 'Title insurance', definition: 'Protects against title defects existing at closing.', category: 'title' },
  { term: 'TMK', definition: 'Tax Map Key. Hawaii\'s parcel ID: Zone-Section-Plat-Parcel(-CPR).', category: 'hawaii' },
  { term: 'Trust account', definition: 'Separate account for client/customer funds. No commingling.', category: 'agency' },
  { term: 'Truth in Lending Act / Reg Z', definition: 'Federal law requiring APR disclosure and standardized loan cost format.', category: 'finance' },
  { term: 'Unilateral contract', definition: 'One party makes a promise; other accepts by performance (e.g., reward).', category: 'contracts' },
  { term: 'Universal agent', definition: 'Authority to act in all matters. Power of attorney.', category: 'agency' },
  { term: 'Usury', definition: 'Charging interest above legal cap. HRS 478 in Hawaii.', category: 'hawaii' },
  { term: 'VA loan', definition: 'Veterans Affairs guaranteed loan. No PMI; often no down payment.', category: 'finance' },
  { term: 'Variance', definition: 'Narrow exception to zoning for unique hardship.', category: 'national' },
  { term: 'Voidable contract', definition: 'Contract one party can elect to void (e.g., minor\'s contract).', category: 'contracts' },
  { term: 'Warrantable condo', definition: 'Project meeting Fannie/Freddie standards. Easier to finance.', category: 'finance' },
  { term: 'Warranty deed', definition: 'Deed with grantor warranties of title quality.', category: 'title' },
  { term: 'Zoning', definition: 'Public regulation dividing land into use districts.', category: 'national' },
];
